language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t achhouy/react-test -f ./client/Dockerfile.dev ./client

script:
    # - docker run achhouy/react-test npm test -- --coverage
    - docker run -e CI=true achhouy/react-test npm test

after_success:
    - docker build -t achhouy/multi-client ./client
    - docker build -t achhouy/multi-nginx ./nginx
    - docker build -t achhouy/multi-server ./server
    - docker build -t achhouy/multi-worker ./worker
