language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t achhouy/react-test -f ./client/Dockerfile.dev ./client

script:
    # - docker run achhouy/react-test npm test -- --coverage
    - docker run -e CI=true achhouy/react-test npm test

after_success:
    - docker build -t achhuoy/multi-client ./client
    - docker build -t achhuoy/multi-nginx ./nginx
    - docker build -t achhuoy/multi-server ./server
    - docker build -t achhuoy/multi-worker ./worker

    # Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
    - docker push achhuoy/multi-client
    - docker push achhuoy/multi-nginx
    - docker push achhuoy/multi-server
    - docker push achhuoy/multi-worker
